/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze-purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ürün satın alımını 5 ajanla analiz et
         * @description Ürün, yorum, fiyat geçmişi, bütçe ve oturum bilgisini alır; yeşil/sarı/kırmızı bir karar ve 3 gerekçe döner. `priceHistory` boş ise sunucu, ürün URL'sine ait crowdsource veritabanından son 90 günü çeker.
         */
        post: operations["analyze_purchase_api_analyze_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze-purchase/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aynı analiz, ajan tamamlanma olaylarını NDJSON ile streamler
         * @description Her satır bağımsız bir JSON nesnesidir (`application/x-ndjson`). Sıra: 4 paralel sinyal ajanı için `node_finished`, ardından decision için `node_finished`, en sonda `verdict` (tam AnalyzeResponse). Hata olursa son satır `error` olur. Karar mantığı normal endpoint ile aynıdır; tek fark stream şeklidir.
         */
        post: operations["analyze_purchase_stream_api_analyze_purchase_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gemini cache içeriğini boşalt (admin)
         * @description Hedefli temizleme: ?userId=... verilirse o kullanıcıya ait, ?url=... verilirse o URL'ye ait kayıtlar düşürülür. Hiçbiri verilmezse tüm cache temizlenir. THUNDRLY_ADMIN_TOKEN gerekli (tanımlı değilse açık).
         */
        post: operations["cache_purge_api_cache_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gemini cache hit/miss istatistikleri
         * @description Bellek içi Gemini response cache'inin sayaçlarını döner. Hit oranı, evictions ve invalidations metriklerini gözlemlemek için kullan. THUNDRLY_ADMIN_TOKEN tanımlıysa Authorization header'ında geçirilmesi gerekir; tanımlı değilse herkese açık.
         */
        get: operations["cache_stats_api_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Process is up. Cheap; always 200 if the FastAPI worker can handle a request at all. The `gemini` field signals whether the review + decision agents will actually call the LLM (true) or fall back to the deterministic heuristic (false) — the extension popup pings this so the user can verify their installation.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price-observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crowdsource fiyat gözlemi kaydet
         * @description Eklenti her ürün sayfası açılışında o anki fiyatı bu uca POST eder. Sunucu URL'yi normalize edip append-only saklar; aynı ürünün ileride yapılan analizleri bu geçmişten beslenir. Rate-limit: IP başına 60/dakika.
         */
        post: operations["post_price_observation_api_price_observation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kullanıcının taahhüt ettiği bir satın almayı kaydet
         * @description Eklenti `Yine de Devam Et` tıklandığında bu uca POST eder. (userId, category) için `category_spent` toplamına `amount` eklenir; gelecekteki analizler bu güncel toplamı kullanır. Ay sonunda satırlar lazily resetlenir.
         */
        post: operations["post_purchase_api_purchases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Process is up AND the database is reachable. Returns 503 if the DB connection fails, so an orchestrator can hold traffic off until migrations finish on first boot.
         */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kullanıcı bütçesini (kategori bazlı) getir
         * @description (userId, category) çifti için saklanan bütçeyi döner. Eşleşen kayıt yoksa permissive bir varsayılan döner; budget_agent böylelikle her zaman skorlayacak bir veri bulur.
         */
        get: operations["get_user_budget_api_user_budget_get"];
        /**
         * Kullanıcı bütçesini (kategori bazlı) kaydet/güncelle
         * @description (userId, category) için upsert. Aynı çiftte birden fazla satır olmaz.
         */
        put: operations["put_user_budget_api_user_budget_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-budget/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kullanıcının genel aylık bütçesini getir
         * @description Hibrit bütçe modelinde **birincil** alan. Kullanıcı yalnızca bu değeri girerse de bütçe ajanı tüm satın almaları bu envelope'a karşı puanlar. Kayıt yoksa permissive bir varsayılan döner.
         */
        get: operations["get_user_budget_global_api_user_budget_global_get"];
        /**
         * Kullanıcının genel aylık bütçesini kaydet
         * @description GLOBAL sentinel satırını upsert eder. ``categoryLimit`` otomatik olarak ``monthlyLimit`` değerine eşitlenir. Per-category satırlar isteğe bağlı, ayrı uçla yönetilir.
         */
        put: operations["put_user_budget_global_api_user_budget_global_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kullanıcının tüm bütçe özetini getir (popup için)
         * @description Tek kullanıcı için aylık limit + her kategori limiti ve mevcut ay harcaması döner. GLOBAL sentinel satırı listede yer almaz; aylık genel limit ayrı bir alanda döner. Hiç kayıt yoksa boş özet döner (categories=[], spent=0).
         */
        get: operations["get_user_budgets_summary_api_user_budgets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentFinding */
        AgentFinding: {
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "risk";
            /** Tag */
            tag?: string | null;
        };
        /** AgentResult */
        AgentResult: {
            /** Findings */
            findings?: components["schemas"]["AgentFinding"][];
            /** Label */
            label: string;
            /** Score */
            score: number;
        };
        /** AgentResultMap */
        AgentResultMap: {
            budgetAgent: components["schemas"]["AgentResult"];
            decisionAgent: components["schemas"]["AgentResult"];
            impulseAgent: components["schemas"]["AgentResult"];
            priceAgent: components["schemas"]["AgentResult"];
            reviewAgent: components["schemas"]["AgentResult"];
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Platform */
            platform: string;
            /** Pricecomparisons */
            priceComparisons?: components["schemas"]["PriceComparisonOffer"][];
            /** Pricehistory */
            priceHistory?: components["schemas"]["PriceHistoryPoint"][];
            product: components["schemas"]["Product"];
            /** Reviews */
            reviews?: components["schemas"]["Review"][];
            session: components["schemas"]["SessionContext"];
            userBudget?: components["schemas"]["UserBudget"] | null;
            /** Userid */
            userId: string;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            agents: components["schemas"]["AgentResultMap"];
            /**
             * Decision
             * @enum {string}
             */
            decision: "green" | "yellow" | "red";
            /** Reasons */
            reasons: string[];
            /** Recommendedaction */
            recommendedAction: string;
            /** Riskscore */
            riskScore: number;
            /** Summary */
            summary: string;
            /** Triggeredrules */
            triggeredRules?: components["schemas"]["TriggeredRule"][];
        };
        /**
         * CategoryBudget
         * @description One row in the user's budget — name + limit + current-period spend.
         */
        CategoryBudget: {
            /** Category */
            category: string;
            /** Categorylimit */
            categoryLimit: number;
            /** Categoryspent */
            categorySpent: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PriceComparisonOffer
         * @description Current-market offer from an external comparison/search source.
         */
        PriceComparisonOffer: {
            /** Price */
            price: number;
            /** Source */
            source: string;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** PriceHistoryPoint */
        PriceHistoryPoint: {
            /** Date */
            date: string;
            /** Price */
            price: number;
        };
        /**
         * PriceObservationIn
         * @description Payload from the extension on every product-page load.
         */
        PriceObservationIn: {
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Price */
            price: number;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /**
         * PriceObservationOut
         * @description Acknowledgement returned to the extension.
         */
        PriceObservationOut: {
            /** Canonicalurl */
            canonicalUrl: string;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Platform */
            platform: string;
            /** Storedat */
            storedAt: string;
        };
        /** Product */
        Product: {
            /** Category */
            category: string;
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Imageurl */
            imageUrl?: string | null;
            /** Legallowestprice30D */
            legalLowestPrice30d?: number | null;
            /** Originalprice */
            originalPrice?: number | null;
            /** Price */
            price: number;
            /** Rating */
            rating?: number | null;
            /** Reviewcount */
            reviewCount?: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * PurchaseIn
         * @description Recorded when the user clicks 'Yine de Devam Et' in the panel.
         *
         *     Treated as a committed purchase; the backend bumps the running
         *     `category_spent` total for (userId, category) by `amount`.
         */
        PurchaseIn: {
            /** Amount */
            amount: number;
            /** Category */
            category: string;
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Userid */
            userId: string;
        };
        /** PurchaseOut */
        PurchaseOut: {
            /** Category */
            category: string;
            /** Categorylimit */
            categoryLimit: number;
            /** Categoryspent */
            categorySpent: number;
            /** Monthlylimit */
            monthlyLimit: number;
            /** Monthlyspent */
            monthlySpent: number;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Periodstart */
            periodStart: string;
            /** Userid */
            userId: string;
        };
        /** Review */
        Review: {
            /** Author */
            author?: string | null;
            /** Date */
            date: string;
            /** Helpfulcount */
            helpfulCount?: number | null;
            /** Rating */
            rating: number;
            /** Text */
            text: string;
            /** Verifiedpurchase */
            verifiedPurchase?: boolean | null;
        };
        /** SessionContext */
        SessionContext: {
            /** Clickspeedms */
            clickSpeedMs: number;
            /** Currenthour */
            currentHour: number;
            /** Purchasestoday */
            purchasesToday: number;
            /** Searchedbefore */
            searchedBefore?: boolean | null;
            /** Timeonpageseconds */
            timeOnPageSeconds: number;
        };
        /**
         * TriggeredRule
         * @description One causal rule that fired in the decision pass.
         *
         *     The rule engine evaluates AND/OR combinations over tagged findings
         *     (e.g. ``suspiciousDiscount + lowReviewTrust``) and emits one of these
         *     for each rule it triggered. The panel renders them as a small
         *     "Tetiklenen kurallar" section so the user can see WHY the verdict
         *     landed where it did beyond the bare risk score.
         */
        TriggeredRule: {
            /** Explanation */
            explanation: string;
            /** Name */
            name: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "risk";
        };
        /** UserBudget */
        UserBudget: {
            /** Categorylimit */
            categoryLimit: number;
            /** Categoryspent */
            categorySpent: number;
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Monthlylimit */
            monthlyLimit: number;
            /** Monthlyspent */
            monthlySpent?: number | null;
        };
        /**
         * UserBudgetSummary
         * @description All of a user's budget data, suitable for the popup UI.
         */
        UserBudgetSummary: {
            /** Categories */
            categories: components["schemas"]["CategoryBudget"][];
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Monthlylimit */
            monthlyLimit: number;
            /** Monthlyspent */
            monthlySpent: number;
            /** Periodstart */
            periodStart: string;
            /** Userid */
            userId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_purchase_api_analyze_purchase_post: {
        parameters: {
            query?: {
                /** @description True olduğunda Gemini yanıt cache'i atlanır — kullanıcı panelden 'Yeniden analiz et' istediğinde gönder. */
                force_refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_purchase_stream_api_analyze_purchase_stream_post: {
        parameters: {
            query?: {
                force_refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_purge_api_cache_purge_post: {
        parameters: {
            query?: {
                userId?: string | null;
                url?: string | null;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_stats_api_cache_stats_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    post_price_observation_api_price_observation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceObservationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceObservationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_purchase_api_purchases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_user_budget_api_user_budget_get: {
        parameters: {
            query: {
                userId: string;
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_user_budget_api_user_budget_put: {
        parameters: {
            query: {
                userId: string;
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBudget"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_budget_global_api_user_budget_global_get: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_user_budget_global_api_user_budget_global_put: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBudget"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_budgets_summary_api_user_budgets_get: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBudgetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
