/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze-purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ürün satın alımını 5 ajanla analiz et
         * @description Ürün, yorum, fiyat geçmişi, bütçe ve oturum bilgisini alır; yeşil/sarı/kırmızı bir karar ve 3 gerekçe döner. `priceHistory` boş ise sunucu, ürün URL'sine ait crowdsource veritabanından son 90 günü çeker.
         */
        post: operations["analyze_purchase_api_analyze_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze-purchase/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aynı analiz, ajan tamamlanma olaylarını NDJSON ile streamler
         * @description Her satır bağımsız bir JSON nesnesidir (`application/x-ndjson`). Sıra: 4 paralel sinyal ajanı için `node_finished`, ardından decision için `node_finished`, en sonda `verdict` (tam AnalyzeResponse). Hata olursa son satır `error` olur. Karar mantığı normal endpoint ile aynıdır; tek fark stream şeklidir.
         */
        post: operations["analyze_purchase_stream_api_analyze_purchase_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Process is up. Cheap; always 200 if the FastAPI worker can handle a request at all. Use for load-balancer health checks.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price-observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crowdsource fiyat gözlemi kaydet
         * @description Eklenti her ürün sayfası açılışında o anki fiyatı bu uca POST eder. Sunucu URL'yi normalize edip append-only saklar; aynı ürünün ileride yapılan analizleri bu geçmişten beslenir. Rate-limit: IP başına 60/dakika.
         */
        post: operations["post_price_observation_api_price_observation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Process is up AND the database is reachable. Returns 503 if the DB connection fails, so an orchestrator can hold traffic off until migrations finish on first boot.
         */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kullanıcı bütçesini (kategori bazlı) getir
         * @description (userId, category) çifti için saklanan bütçeyi döner. Eşleşen kayıt yoksa permissive bir varsayılan döner; budget_agent böylelikle her zaman skorlayacak bir veri bulur.
         */
        get: operations["get_user_budget_api_user_budget_get"];
        /**
         * Kullanıcı bütçesini (kategori bazlı) kaydet/güncelle
         * @description (userId, category) için upsert. Aynı çiftte birden fazla satır olmaz.
         */
        put: operations["put_user_budget_api_user_budget_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentFinding */
        AgentFinding: {
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "risk";
        };
        /** AgentResult */
        AgentResult: {
            /** Findings */
            findings?: components["schemas"]["AgentFinding"][];
            /** Label */
            label: string;
            /** Score */
            score: number;
        };
        /** AgentResultMap */
        AgentResultMap: {
            budgetAgent: components["schemas"]["AgentResult"];
            decisionAgent: components["schemas"]["AgentResult"];
            impulseAgent: components["schemas"]["AgentResult"];
            priceAgent: components["schemas"]["AgentResult"];
            reviewAgent: components["schemas"]["AgentResult"];
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Platform */
            platform: string;
            /** Pricehistory */
            priceHistory?: components["schemas"]["PriceHistoryPoint"][];
            product: components["schemas"]["Product"];
            /** Reviews */
            reviews?: components["schemas"]["Review"][];
            session: components["schemas"]["SessionContext"];
            userBudget?: components["schemas"]["UserBudget"] | null;
            /** Userid */
            userId: string;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            agents: components["schemas"]["AgentResultMap"];
            /**
             * Decision
             * @enum {string}
             */
            decision: "green" | "yellow" | "red";
            /** Reasons */
            reasons: string[];
            /** Recommendedaction */
            recommendedAction: string;
            /** Riskscore */
            riskScore: number;
            /** Summary */
            summary: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PriceHistoryPoint */
        PriceHistoryPoint: {
            /** Date */
            date: string;
            /** Price */
            price: number;
        };
        /**
         * PriceObservationIn
         * @description Payload from the extension on every product-page load.
         */
        PriceObservationIn: {
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Price */
            price: number;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /**
         * PriceObservationOut
         * @description Acknowledgement returned to the extension.
         */
        PriceObservationOut: {
            /** Canonicalurl */
            canonicalUrl: string;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Platform */
            platform: string;
            /** Storedat */
            storedAt: string;
        };
        /** Product */
        Product: {
            /** Category */
            category: string;
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Imageurl */
            imageUrl?: string | null;
            /** Originalprice */
            originalPrice?: number | null;
            /** Price */
            price: number;
            /** Rating */
            rating?: number | null;
            /** Reviewcount */
            reviewCount?: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** Review */
        Review: {
            /** Author */
            author?: string | null;
            /** Date */
            date: string;
            /** Rating */
            rating: number;
            /** Text */
            text: string;
        };
        /** SessionContext */
        SessionContext: {
            /** Clickspeedms */
            clickSpeedMs: number;
            /** Currenthour */
            currentHour: number;
            /** Purchasestoday */
            purchasesToday: number;
            /** Searchedbefore */
            searchedBefore?: boolean | null;
            /** Timeonpageseconds */
            timeOnPageSeconds: number;
        };
        /** UserBudget */
        UserBudget: {
            /** Categorylimit */
            categoryLimit: number;
            /** Categoryspent */
            categorySpent: number;
            /**
             * Currency
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            /** Monthlylimit */
            monthlyLimit: number;
            /** Monthlyspent */
            monthlySpent?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_purchase_api_analyze_purchase_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_purchase_stream_api_analyze_purchase_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    post_price_observation_api_price_observation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceObservationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceObservationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_user_budget_api_user_budget_get: {
        parameters: {
            query: {
                userId: string;
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_user_budget_api_user_budget_put: {
        parameters: {
            query: {
                userId: string;
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBudget"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
